name: GitHub Actions
run-name: ${{ github.actor }} is running actions 🚀
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        if: always()
        run: npm run build:prod
      - name: linting typescript
        if: always()
        run: npm run lint:ts
      - name: linting scss
        if: always()
        run: npm run lint:scss
      - name: test unit
        if: always()
        run: npm run test:unit
      - name: storybook build
        if: always()
        run: npm run storybook:build
#      - name: test ui
#        if: always()
#        run: npm run test:ui:ci


